export const Quotes = [
    { id: 1, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
    { id: 2, text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
    { id: 3, text: 'Success is not final, failure is not fatal: It is the courage to continue that counts.', author: 'Winston Churchill' },
    { id: 4, text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
    { id: 5, text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
    { id: 6, text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
    { id: 7, text: 'The only limit to our realization of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt' },
    { id: 8, text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar' },
    { id: 9, text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
    { id: 10, text: 'The journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
    { id: 11, text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
    { id: 12, text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
    { id: 13, text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
    { id: 14, text: 'I have not failed. I’ve just found 10,000 ways that won’t work.', author: 'Thomas Edison' },
    { id: 15, text: 'Everything you’ve ever wanted is on the other side of fear.', author: 'George Addair' },
    { id: 16, text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
    { id: 17, text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
    { id: 18, text: 'Opportunities don’t happen. You create them.', author: 'Chris Grosser' },
    { id: 19, text: 'Don’t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
    { id: 20, text: 'The harder you work for something, the greater you’ll feel when you achieve it.', author: 'Anonymous' },
    { id: 21, text: 'Dream big and dare to fail.', author: 'Norman Vaughan' },
    { id: 22, text: 'It’s not whether you get knocked down, it’s whether you get up.', author: 'Vince Lombardi' },
    { id: 23, text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
    { id: 24, text: 'What we achieve inwardly will change outer reality.', author: 'Plutarch' },
    { id: 25, text: 'Believe in yourself and all that you are.', author: 'Christian D. Larson' },
    { id: 26, text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
    { id: 27, text: 'Your time is limited, so don’t waste it living someone else’s life.', author: 'Steve Jobs' },
    { id: 28, text: 'The mind is everything. What you think you become.', author: 'Buddha' },
    { id: 29, text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
    { id: 30, text: 'Don’t let yesterday take up too much of today.', author: 'Will Rogers' },
    { id: 31, text: 'You are never too small to make a difference.', author: 'Greta Thunberg' },
    { id: 32, text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
    { id: 33, text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
    { id: 34, text: 'Happiness is not something ready-made. It comes from your own actions.', author: 'Dalai Lama' },
    { id: 35, text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
    { id: 36, text: 'Life is what happens when you’re busy making other plans.', author: 'John Lennon' },
    { id: 37, text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson' },
    { id: 38, text: 'Keep your face always toward the sunshine—and shadows will fall behind you.', author: 'Walt Whitman' },
    { id: 39, text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr.' },
    { id: 40, text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
    { id: 41, text: 'You don’t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
    { id: 42, text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
    { id: 43, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
    { id: 44, text: 'Success is not the key to happiness. Happiness is the key to success.', author: 'Albert Schweitzer' },
    { id: 45, text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
    { id: 46, text: 'The greatest wealth is to live content with little.', author: 'Plato' },
    { id: 47, text: 'Do not wait to strike till the iron is hot, but make it hot by striking.', author: 'William Butler Yeats' },
    { id: 48, text: 'The best way out is always through.', author: 'Robert Frost' },
    { id: 49, text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
    { id: 50, text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt' },
    { id: 51, text: 'Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears.', author: 'Chantal Sutherland' },
    { id: 52, text: 'The future starts today, not tomorrow.', author: 'Pope John Paul II' },
    { id: 53, text: 'You are enough just as you are.', author: 'Meghan Markle' },
    { id: 54, text: 'The most difficult thing is the decision to act, the rest is merely tenacity.', author: 'Amelia Earhart' },
    { id: 55, text: 'Don’t let the fear of losing be greater than the excitement of winning.', author: 'Robert Kiyosaki' },
    { id: 56, text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
    { id: 57, text: 'The biggest risk is not taking any risk.', author: 'Mark Zuckerberg' },
    { id: 58, text: 'Your life does not get better by chance, it gets better by change.', author: 'Jim Rohn' },
    { id: 59, text: 'The only person you should try to be better than is the person you were yesterday.', author: 'Anonymous' },
    { id: 60, text: 'Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.', author: 'Booker T. Washington' },
    { id: 61, text: 'You don’t have to see the whole staircase, just take the first step.', author: 'Martin Luther King Jr.' },
    { id: 62, text: 'The real test is not whether you avoid this failure, because you won’t. It’s whether you let it harden or shame you into inaction, or whether you learn from it.', author: 'Barack Obama' },
    { id: 63, text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
    { id: 64, text: 'It’s not about how bad you want it. It’s about how hard you’re willing to work for it.', author: 'Anonymous' },
    { id: 65, text: 'The harder the conflict, the more glorious the triumph.', author: 'Thomas Paine' },
    { id: 66, text: 'What we think, we become.', author: 'Buddha' },
    { id: 67, text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
    { id: 68, text: 'Dreams are the seeds of change. Nothing ever grows without a seed, and nothing ever changes without a dream.', author: 'Debby Boone' },
    { id: 69, text: 'The key to success is to focus on goals, not obstacles.', author: 'Anonymous' },
    { id: 70, text: 'You are never given a dream without also being given the power to make it true.', author: 'Richard Bach' },
    { id: 71, text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
    { id: 72, text: 'Don’t wait. The time will never be just right.', author: 'Napoleon Hill' },
    { id: 73, text: 'Success is not in what you have, but who you are.', author: 'Bo Bennett' },
    { id: 74, text: 'The best way to find yourself is to lose yourself in the service of others.', author: 'Mahatma Gandhi' },
    { id: 75, text: 'Believe and act as if it were impossible to fail.', author: 'Charles Kettering' },
    { id: 76, text: 'Great things never come from comfort zones.', author: 'Anonymous' },
    { id: 77, text: 'The only way to achieve the impossible is to believe it is possible.', author: 'Charles Kingsleigh' },
    { id: 78, text: 'Your passion is waiting for your courage to catch up.', author: 'Isabelle Lafleche' },
    { id: 79, text: 'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.', author: 'Mark Caine' },
    { id: 80, text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T. Bennett' },
    { id: 81, text: 'The only limit to your impact is your imagination and commitment.', author: 'Tony Robbins' },
    { id: 82, text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
    { id: 83, text: 'You are braver than you believe, stronger than you seem, and smarter than you think.', author: 'A.A. Milne' },
    { id: 84, text: 'The best way to cheer yourself is to try to cheer someone else up.', author: 'Mark Twain' },
    { id: 85, text: 'Don’t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
    { id: 86, text: 'Happiness is not having what you want, but wanting what you have.', author: 'Hyman Schachtel' },
    { id: 87, text: 'The greatest risk is not taking one.', author: 'Tim Ferriss' },
    { id: 88, text: 'What you seek is seeking you.', author: 'Rumi' },
    { id: 89, text: 'The purpose of life is a life of purpose.', author: 'Robert Byrne' },
    { id: 90, text: 'You don’t drown by falling in the water; you drown by staying there.', author: 'Edwin Louis Cole' },
    { id: 91, text: 'The secret of success is constancy to purpose.', author: 'Benjamin Disraeli' },
    { id: 92, text: 'Life is short, and it is up to you to make it sweet.', author: 'Sarah Louise Delany' },
    { id: 93, text: 'The only way to do it is to do it.', author: 'Merce Cunningham' },
    { id: 94, text: 'Your present circumstances don’t determine where you can go; they merely determine where you start.', author: 'Nido Qubein' },
    { id: 95, text: 'Success is not measured by what you accomplish, but by the opposition you have encountered.', author: 'Orison Swett Marden' },
    { id: 96, text: 'The most effective way to do it, is to do it.', author: 'Amelia Earhart' },
    { id: 97, text: 'You have within you, right now, everything you need to deal with whatever the world can throw at you.', author: 'Brian Tracy' },
    { id: 98, text: 'The best dreams happen when you’re awake.', author: 'Cherie Gilderbloom' },
    { id: 99, text: 'Don’t let what you cannot do interfere with what you can do.', author: 'John Wooden' },
    { id: 100, text: 'The greatest pleasure in life is doing what people say you cannot do.', author: 'Walter Bagehot' },
];
